name: on-commit
on:
  push:
    paths:
      - 'Dockerfile'
      - 'config.toml'
      - 'assets/**'
      - 'content/**'
      - 'layouts/**'
      - 'resources/**'
      - 'static/**'
      - 'themes/**'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  bump_tag:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      # GitHub Action: https://github.com/marketplace/actions/github-tag-bump
      uses: anothrNick/github-tag-action@1.75.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        DEFAULT_BRANCH: main
        WITH_V: false
 
  changelog:
    needs: bump_tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Generate and Commit Changelog

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Generate Changelog
      uses: smichard/conventional_changelog@2.0.8
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Git User Info
      run: |
        git config user.name 'GitHub Actions Bot'
        git config user.email 'actions@github.com'

    - name: Commit Changelog
      run: |
        git add CHANGELOG.md
        git commit -m "docs: :robot: changelog file generated" || echo "No changes to commit"
        git push

  build_and_push:
    needs: changelog
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Log in to target registry
      run: |
        echo ${{ secrets.TARGET_REGISTRY_PASSWORD }} | docker login quay.io -u ${{ secrets.TARGET_REGISTRY_USERNAME }} --password-stdin

    - name: Get tag from bumped version
      id: tag
      run: |
        # Fetch the latest changes
        git fetch --tags
        TAG=$(git describe --tags --abbrev=0 || echo "latest")
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "Current build tag: $TAG"

    - name: Get git submodules
      id: submodules
      run: |
        git submodule update --init --recursive

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build container image and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64
        push: true
        tags: quay.io/michard/hugo_website:${{ env.TAG }},quay.io/michard/hugo_website:latest